language: node_js
node_js:
    - lts/*

cache:
    yarn: true

before_script:
    - yarn setup

script:
    - yarn build
    - yarn test
    - yarn coverage

before_deploy:
    - mkdir -p public
    - yarn typedoc
    - cp -r typedoc/* public/
    - cp -r coverage public/

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local_dir: public
    committer-from-gh: true
    verbose: true
    on:
        branch: master
